name: contextos
run-name: Ejecutando practica de contextos
on: push #push
jobs:
  check-branch:
    if: ${{github.ref == 'refs/heads/aprendiendo-github-action'}}
    runs-on: ubuntu-lastest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
