name: contextos
run-name: Ejecutando practica de contextos
on: push #push
jobs:
  check-main:
    if: ${{github.ref != 'refs/heads/main'}}
    runs-on: ubuntu-lastest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
