name: Expression

on:
  workflow_dispatch:
    inputs:
      edad:
        description: Edad
        required: true
        type: integer
      nombre:
        description: Tu nombre
        required: true
        default: NN
        type: string

jobs:
  mayor:
    runs-on: ubuntu-latest
    if: ${{ inputs.edad >= 18 }}
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es mayor de edad

  menor:
    runs-on: ubuntu-latest
    if: ${{ inputs.edad < 18 }}
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es menor de edad

