---
name: Secrets in GitHub
run-name: Aprendiendo a usar secretos
on:
  workflow_dispatch:
    inputs:
      numero:
        description: número
        required: true
        type: integer
jobs:
  Descubrir_el_mensaje:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Mi nombre es clasificado
    if: ${{ secrets.SECRET_NUMBER == inputs.numero }}
    steps:
      - name: Mensaje desbloqueado
        run: echo ${{ env.MESSAGE }}
  Autodestruccion:
    runs-on: ubuntu-latest
    if: ${{ secrets.SECRET_NUMBER != inputs.numero }}
    steps:
      - name: LA REGASTE
        run: echo "Este computador se autodestruirá"
