name: Top-Secret
run-name: Aprendiendo Secretos
on:
  workflow_dispatch:
    inputs:
      numero:
        description: Número
        required: true
        type: integer

jobs:
  Validar_contrasena:
    runs-on: ubuntu-latest
    steps:
      - name: Validar valor de numero
        run: echo "El número ingresado es $inputs.numero"
      - name: Validar Contraseña
        run: |
          if "${{ inputs.numero == 1 }}"; then
            echo "Mi nombre es CLASIFICADO"
            echo "Se ingresa la contraseña .|. $secrets.SECRET_NUMBER .|."
          else
            echo "Su computadora se destruirá en 5 segundos."
          fi
