name: Top-Secret
run-name: Aprendiendo Secretos
on:
  workflow_dispatch:
    inputs:
      numero:
        description: Número
        required: true
        type: integer

jobs:
  Validar_contrasena:
    runs-on: ubuntu-latest
    steps:
      - name: Validar Contraseña
        run: |
          if [ "${{ secrets.SECRET_NUMBER }}" -eq "${{ inputs.numbero }}" ]; then
            echo "Mi nombre es CLASIFICADO"
          else
            echo "Su computadora se destruirá en 5 segundos."
          fi
